Remove mentions to async handlers in exercises not about handling errors
codeplaysoftware/syclacademy pull request #180
Opened 2022-08-25 16:18 UTC by hdelan

I think this should go into main. 

Queues in SYCL 2020 are constructed with a default async handler. We do not need to construct these by hand in every exercise.

2022-08-26 13:15 UTC, AerialMantis approved these changes
LGTM, thanks! We should create a ticket for adding an more advanced exercises later on creating an async_handler.

2022-09-07 09:49 UTC, joeatodd requested changes
Minor point - some default_selectors removed, is this intentional?

2022-09-07 09:49 UTC, joeatodd commented on Code_Exercises/Exercise_06_Vector_Add/solution.cpp
> +    auto defaultQueue = sycl::queue{};
You've also gotten rid of the sycl::default_selector{} here, which I guess ought to remain?

2022-09-07 09:49 UTC, joeatodd commented on Code_Exercises/Exercise_09_Synchronization/solution.cpp
> +    auto defaultQueue = sycl::queue{};
Same here, default_selector removed?

2022-09-07 09:49 UTC, joeatodd commented on Code_Exercises/Exercise_10_Managing_Dependencies/solution.cpp
> +    auto defaultQueue = sycl::queue{};
ditto

2022-10-05 14:13 UTC, merged